### PR TITLE
added f() methods in c++, including a new one that takes a string prototxt

### PR DESCRIPTION
**Pull request by nicodjimenez**

### CODE REVIEW

**Comment by Russell91** [comment]
We'll need to change definitions.pxd and _apollocaffe.pyx before merging this.

**Comment by nicodjimenez** [comment]
Are you thinking of changing the following? 

```python
    def f(self, layer):
        if isinstance(layer, str):
            # create LayerParameter from string
            from apollocaffe.proto import caffe_pb2
            p = caffe_pb2.LayerParameter()
            Merge(layer, p)
            loss = self.thisptr.ForwardLayer(p.SerializeToString())
```

**Comment by Russell91** [comment]
Yea, I'm just suggesting that if you want to rename ForwardLayer in one place, we should do it for the rest as well. That involves a find/replace of ForwardLayer with f in both _apollocaffe.pyx and definitions.pxd

**Comment by Russell91** [comment]
This will actually be pretty nice too as both python and c++ f() methods will have 3 overloads:

1) You can pass a prototxt string
2) You can pass a protobuf LayerParameter
3) You can pass a layer object

**Comment by nicodjimenez** [comment]
I can't replace ForwardLayer with f() everywhere because both methods take a string, but ForwardLayer deserializes it whereas f() does not do so.  Makes sense? From apollonet.cpp:
```c++
  Dtype ForwardLayer(const string& layer_param_string);

  Dtype f(shared_ptr<Layer<Dtype> > layer);

  Dtype f(const string layer_prototxt);
```

**Comment by Russell91** [comment]
Okay, I hadn't thought about that. Of course we could try to detect whether the string being passed was a serialized protobuf and dispatch accordingly in the c++, but that would feel weird. Do you have any other ideas we could use to make things more uniform?

Also, is there a reason you're not passing the layer_prototxt by reference?

**Comment by nicodjimenez** [comment]
well right now things are kind of uniform aren't they? we have two operator overloads for f() in c++ in python.  

No good reason not to pass by reference by i'll change that.

**Pull request merged**
